# Generated by Django 4.1.7 on 2023-03-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_cart_course_id_alter_wishlist_course_id'),
        ('Admin', '0005_order_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.cart'),
        ),
    ]
