# Generated by Django 4.1.7 on 2023-03-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0011_course_completed'),
        ('Admin', '0008_remove_orders_order_cart_orders_order_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Tutor.course'),
        ),
    ]
