# Generated by Django 4.1.7 on 2023-02-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutors'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Price',
            new_name='price',
        ),
    ]
