# Generated by Django 4.1.7 on 2023-03-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0003_alter_skills_options_alter_tutor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='rating',
        ),
    ]
