# Generated by Django 4.1.7 on 2023-03-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0004_remove_tutor_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Level',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='course',
            name='Rating',
            field=models.BigIntegerField(default=0),
        ),
    ]
