# Generated by Django 4.1.7 on 2023-03-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0005_rename_level_course_level_alter_course_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(choices=[('1', '1 month'), ('2', '2 month'), ('3', '3 month'), ('4', '4 month'), ('5', '5 month'), ('6', '6 month'), ('7', '7 month'), ('8', '8 month'), ('9', '9 month')]),
        ),
    ]
