# Generated by Django 4.1.7 on 2023-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0006_rename_rating_course_rating_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (4, '4 months'), (5, '5 months'), (6, '6 months'), (7, '7 months'), (8, '8 months'), (9, '9 months')]),
        ),
    ]
