# Generated by Django 4.1.7 on 2023-03-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0007_tutor_mobile_alter_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='Chapters')),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutor.course')),
            ],
        ),
    ]
