# Generated by Django 4.1.7 on 2023-03-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0008_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chapters',
            field=models.CharField(choices=[(2, '2 chapters'), (3, '3 chapters'), (4, '4 chapters'), (5, '5 chapters'), (6, '6 chapters'), (7, '7 chapters'), (8, '8 chapters'), (9, '9 chapters'), (10, '10 chapters')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam'), ('Hindi', 'Hindi')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='Tutor.course'),
        ),
    ]
