# Generated by Django 4.1.7 on 2023-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0015_alter_course_requirements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='skills_offering',
            new_name='related_topics',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('It & Software', 'It & Software'), ('Business & Finance', 'Business & Finance'), ('Health', 'Health & Fitness'), ('Marketing', 'Marketing')], default='', max_length=150),
        ),
    ]
