# Generated by Django 4.1.7 on 2023-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0016_rename_skills_offering_course_related_topics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('It & Software', 'It & Software'), ('Business & Finance', 'Business & Finance'), ('Health', 'Health & Fitness'), ('Marketing', 'Marketing')], max_length=150),
        ),
    ]
