# Generated by Django 4.1.7 on 2023-03-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0019_alter_course_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
