# Generated by Django 4.1.7 on 2023-03-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0022_chapters_read_review_comment_chapters_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutor.comment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutor.review'),
        ),
    ]
