# Generated by Django 4.1.7 on 2023-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0023_alter_chapters_comments_alter_course_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
