# Generated by Django 4.1.7 on 2023-03-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0025_alter_chapters_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapters',
            old_name='comments',
            new_name='comme',
        ),
    ]
