# Generated by Django 4.1.7 on 2023-03-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0026_rename_comments_chapters_comme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='comme',
        ),
        migrations.AddField(
            model_name='chapters',
            name='comments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Tutor.comment'),
        ),
    ]
