# Generated by Django 4.1.7 on 2023-03-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0031_alter_skills_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='category',
        ),
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.ManyToManyField(to='Tutor.categories'),
        ),
    ]
