# Generated by Django 4.1.7 on 2023-03-21 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0032_remove_skills_category_skills_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Tutor.review'),
        ),
    ]
