# Generated by Django 4.1.7 on 2023-03-21 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0035_alter_chapters_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutor.comment'),
        ),
    ]
