# Generated by Django 4.1.7 on 2023-03-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0036_alter_chapters_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='course',
            name='reviews',
        ),
        migrations.AddField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Tutor.chapters'),
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Tutor.course'),
        ),
    ]
