# Generated by Django 4.1.7 on 2023-03-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0038_alter_comment_chapter_alter_review_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
