# Generated by Django 4.1.7 on 2023-03-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0040_comment_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='review_text',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=False),
        ),
    ]
