# Generated by Django 4.1.7 on 2023-03-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0042_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_date',
            field=models.DateField(default='2023-03-21'),
        ),
        migrations.AddField(
            model_name='review',
            name='posted_date',
            field=models.DateField(default='2023-03-21'),
        ),
    ]
