# Generated by Django 4.1.7 on 2023-03-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0045_course_students_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='read',
        ),
    ]
