# Generated by Django 4.1.7 on 2023-03-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0046_remove_chapters_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='qualification',
            field=models.CharField(choices=[('Degree', 'Degree'), ('Msc Computer Science', 'Msc Computer Science'), ('Bsc Computer Science', 'Bsc Computer Science'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('Bsc Biology', 'Bsc Biology'), ('Self Studied', 'Self Studied')], max_length=100),
        ),
    ]
