# Generated by Django 4.1.7 on 2023-02-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_amount', models.FloatField()),
                ('payment_option', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'CARD')], max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
