# Generated by Django 4.1.7 on 2023-02-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
        ('Tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_courses', to='Tutor.course'),
        ),
    ]
