# Generated by Django 4.1.7 on 2023-02-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
