# Generated by Django 4.1.7 on 2023-03-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
