# Generated by Django 4.1.7 on 2023-03-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0007_tutor_mobile_alter_course_duration'),
        ('User', '0008_alter_wishlist_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_courses', to='Tutor.course', unique=True),
        ),
    ]
