# Generated by Django 4.1.7 on 2023-03-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0007_tutor_mobile_alter_course_duration'),
        ('User', '0009_alter_cart_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_courses', to='Tutor.course'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_courses', to='Tutor.course'),
        ),
    ]
