# Generated by Django 4.1.7 on 2023-03-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0047_alter_tutor_qualification'),
        ('User', '0012_read_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read_chapter',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_chapters', to='Tutor.chapters'),
        ),
    ]
